# Generated by Django 6.0 on 2026-01-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunity_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=60, null=True),
        ),
    ]
